<?php

namespace AppBundle\Repository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByAlumnoUser($alumno, $user)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT a FROM AppBundle:User u, AppBundle:Alumno a JOIN u.alumnos ass WHERE ass = a and a.id = :alumno and u.id = :user'
			)
			->setParameter("alumno", $alumno->getId())
			->setParameter("user", $user->getId())
			->getOneOrNullResult();
	}

	public function findByHasUser($alumno)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT u FROM AppBundle:User u JOIN u.alumnos ass WHERE ass = :alumno'
			)
			->setParameter("alumno", $alumno)
			->getOneOrNullResult();
	}
}
