<?php

namespace AppBundle\Repository;

/**
 * CitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAlumnoCita($alumno, $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c, AppBundle:Alumno a WHERE a.id = :alumno and c.id = :cita'
            )
            ->setParameter("cita", $id)
            ->setParameter("alumno", $alumno)
            ->getOneOrNullResult();
    }

    public function findBySolicitudes($alumno)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.alumno = :alumno'
            )
            ->setParameter("alumno", $alumno)
            ->getResult();
    }

    public function findByDisponibles($now)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.expiracion > :now and c.asesor is NULL'
            )
            ->setParameter("now", $now)
            ->getResult();
    }

    public function findByExpiradas($now)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.expiracion <= :now and c.asesor is NULL'
            )
            ->setParameter("now", $now)
            ->getResult();
    }

    public function findByRealizadas($now)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.expiracion <= :now and c.asesor is not NULL'
            )
            ->setParameter("now", $now)
            ->getResult();
    }

    public function findByAsesorRealizadas($asesor, $now)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.expiracion <= :now and c.asesor = :asesor'
            )
            ->setParameter("now", $now)
            ->setParameter("asesor", $asesor)
            ->getResult();
    }

    public function findByAsesorPendientes($asesor, $now)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c WHERE c.expiracion > :now and c.asesor = :asesor'
            )
            ->setParameter("now", $now)
            ->setParameter("asesor", $asesor)
            ->getResult();
    }
}
