<?php

namespace AppBundle\Repository;

/**
 * CitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAlumnoCita($alumno, $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cita c, AppBundle:Alumno a WHERE a.id = :alumno and c.id = :cita'
            )
            ->setParameter("cita", $id)
            ->setParameter("alumno", $alumno)
            ->getOneOrNullResult();
    }
}
