# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\Alumno: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_ASESOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        user_db:
            id: AppBundle\Security\User\OAuthUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: /admin(.*)
            # activate different ways to authenticate
            form_login:
                provider: fos_userbundle
                login_path: /admin/login 
                check_path: /admin/login_check
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%secret%'

            logout:
                path:   /logout
                target: /admin/login
            anonymous: true

            context: my_context

        wsse_secured:
            pattern: ^/
            oauth:
                provider: user_db
                resource_owners:
                    google: "/login/check-google"
                login_path: /login
                check_path: /connect
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: AppBundle\Security\User\OAuthUserProvider

            logout: true
            anonymous: true

            context: my_context
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }